### ISSUE TITLE
mantenedor

### ISSUE THREAD

**Issue by williamgueiros** [ulissesalmeida/cpf#3]
bom dia.

Abri esta issue
https://github.com/williamgueiros/Brcpfcnpj/issues/20

queria saber se esta afim. as vezes ate juntar tudo.

**Comment by ulissesalmeida** [comment]
@williamgueiros oi meu querido!

**_Juntar tudo?_**

Acho que não precisa não.  Tipo, a lib BRCPFCNPJ tem CPF e CNPJ, a interface fas funções tem um estilo diferente. Só criei essa pq eu queria algo só focado em CPF e que tivesse uma interface de um jeito diferente. Só publiquei pq se eu gosto assim, se tiver outras pessoas que gostem assim que usem. Por isso acho importante a BRCPFCNPJ e CPF continuarem existindo, para pessoas que as pessoas escolham o estilo que elas mais gostem e/ou precisem de mais ou diferentes features.

**_Me unir como mantenedor da BRCPFCNPJ?**

Valeu pelo convite mas infelizmente não. Ultimamente estou com pouco tempo, e o pouquinho tempo que sobra eu uso para aplicar e experimentar coisas nesta biblioteca.

**Comment by williamgueiros** [comment]
está tranquilo, e que estou mantendo a mais de anos.
e como sempre digo, chega uma hora que tem que passar para frente.

se mudar de ideia e so dar um toque.
