### ISSUE TITLE
CNPJ validation

### ISSUE THREAD

**Issue by roehst** [ulissesalmeida/cpf#6]
Hi all!

This library looks slick. I wonder if there are any plans to add CNPJ validation as well?

Congrats for the work.

**Comment by ulissesalmeida** [comment]
I had a specific library for CNPJ:
-  https://github.com/ulissesalmeida/cnpj

The goal is to have the same features as CPF. But at the moment is stuck because I'm not working on it at the moment 😂

It has the basic `is_valid?` function but needs more features to be in parity with CPF.

**Comment by roehst** [comment]
Nice :) is it usable in production? I really only need to validate CPFs and CNPJs. What features it misses compared to CPF?

**Comment by ulissesalmeida** [comment]
It's usable in production.

It's missing Ecto integration, and some quality of life features. But the validation itself is good for production 👍🏽

**Comment by ulissesalmeida** [comment]
I'm closing it. Any further discussions, improvements, and features can be done on https://github.com/ulissesalmeida/cnpj library.
